name: binaryen

runs:
  using: composite
  steps:
    - name: Setup binaryen
      shell: bash
      env:
        VERSION: version_119
      run: |
        TOOL_PATH="${RUNNER_TOOL_CACHE:?}/binaryen/${VERSION:?}/${RUNNER_ARCH:?}"
        TOOL_PATH_COMPLETE="${TOOL_PATH}.complete"

        echo "${TOOL_PATH}" >> $GITHUB_PATH
        [ -f "${TOOL_PATH_COMPLETE}" ] && exit 0

        mkdir -p "${TOOL_PATH}"

        curl -L --no-progress-meter --fail-with-body \
          --header "Authorization: Bearer ${{ github.token }}" \
          https://github.com/WebAssembly/binaryen/releases/download/${VERSION}/binaryen-${VERSION}-x86_64-linux.tar.gz \
        | tar zxv -C "${TOOL_PATH}" --strip-components 2 binaryen-${VERSION}/bin/

        touch "${TOOL_PATH_COMPLETE}"
