name: Check

on:
  push:

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Export commit timestamp
        run: echo "SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct)" >> $GITHUB_ENV

      - name: Setup binaryen
        uses: phi-ag/setup-binaryen@a056f5d1378af63ffd958e1e2e3abf0df0175ac8 # v1

      - name: Rustup
        uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1

      - name: Build wasm
        run: ./build.sh

      - name: Upload wasm
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: main.wasm
          path: dist/main.wasm
          retention-days: 5

      - name: Setup wasmtime
        uses: bytecodealliance/actions/wasmtime/setup@9152e710e9f7182e4c29ad218e4f335a7b203613 # v1

      - name: Test wasm
        run: cargo test

      - name: Restore
        uses: ./.github/actions/restore

      - name: Audit
        continue-on-error: true
        run: pnpm audit

      - name: Format
        run: |
          pnpm format:check
          cargo fmt --check

      - name: Lint
        run: |
          pnpm lint
          cargo clippy -- -D warnings

      - name: Typecheck
        run: pnpm typecheck

      - name: Test
        run: pnpm test:coverage

      - name: Build
        run: pnpm build
